# install pip speedtest-cli
# run speedtest-cli in the terminal
"""
~/learn-py-with-projects$ speedtest-cli
Retrieving speedtest.net configuration...
Testing from Google Cloud (35.244.17.114)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Prathamesh Broadband Pvt Ltd (Thane) [14.40 km]: 2.433 ms
Testing download speed................................................................................
Download: 2598.94 Mbit/s
Testing upload speed......................................................................................................
Upload: 50.17 Mbit/s
"""
